name: Build, Test, and Deploy to SharkASP.NET

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./discreetkindnessapp/
        continue-on-error: false

      - name: Build Application
        run: dotnet build --configuration Release --no-restore
        working-directory: ./discreetkindnessapp/
        continue-on-error: false

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ./discreetkindnessapp/
        continue-on-error: false

      - name: Publish Application
        run: dotnet publish -c Release -o publish_output
        working-directory: ./discreetkindnessapp/
        continue-on-error: false

      - name: Deploy to SharkASP.NET via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./discreetkindnessapp/publish_output/
          server-dir: /wwwroot/ 
